### ISSUE TITLE
EOF/NullPointer Exceptions Killing Map Tasks

### ISSUE THREAD

**Issue by drewlanenga** [RevolutionAnalytics/rmr2#102]
I've successfully been able to reproduce an issue I'm experiencing in production with intermittent EOFExceptions and NullPointerExceptions being thrown intermittently during map tasks: https://gist.github.com/1718b181ab2307407b0e

Whether or not the exceptions are thrown appears to be a function of the size of the input values to the mapper.

I'm running Hadoop 2.2.0, R 3.0.3, rmr2 3.1.0, which is supported in the [compatibility documentation](https://github.com/RevolutionAnalytics/rmr2/blob/master/docs/compatibility.md).

**Comment by wzqaustin** [comment]
I encountered the same problem with hadoop-1.2.1 and R3.1.2 and rmr2_3.3.1.

I use -Xmx1G for map task, OOM, while using -Xmx10G, it throws EOFException。
OOMException
[code]
java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:376)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:576)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:135)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:36)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:366)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
	at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.apache.hadoop.typedbytes.TypedBytesInput.readRawBytes(TypedBytesInput.java:212)
	at org.apache.hadoop.typedbytes.TypedBytesInput.readRaw(TypedBytesInput.java:152)
	at org.apache.hadoop.streaming.io.TypedBytesOutputReader.readKeyValue(TypedBytesOutputReader.java:51)
	at org.apache.hadoop.streaming.PipeMapRed$MROutputThread.run(PipeMapRed.java:418)
[/code]


EOFException
[code]
java.lang.RuntimeException: java.io.EOFException
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:376)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:576)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:135)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:36)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:366)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
	at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at org.apache.hadoop.typedbytes.TypedBytesInput.readRawBytes(TypedBytesInput.java:218)
	at org.apache.hadoop.typedbytes.TypedBytesInput.readRaw(TypedBytesInput.java:152)
	at org.apache.hadoop.streaming.io.TypedBytesOutputReader.readKeyValue(TypedBytesOutputReader.java:51)
	at org.apache.hadoop.streaming.PipeMapRed$MROutputThread.run(PipeMapRed.java:418)
[/code]

**Comment by wzqaustin** [comment]
It appears R output format not compatible with java framework. , readRaw() first read code from inputstream, code is 87 for my case, then call  readRawBytes(int code)。readRawBytes(int code) first read length from inputstream , then call readFully(), as below:
<code>
  public byte[] readRawBytes(int code) throws IOException {
    int length = in.readInt();
    LOG.info("Need read " + length + " bytes for code " + code);
    byte[] bytes = new byte[5 + length];
    bytes[0] = (byte) code;
    bytes[1] = (byte) (0xff & (length >> 24));
    bytes[2] = (byte) (0xff & (length >> 16));
    bytes[3] = (byte) (0xff & (length >> 8));
    bytes[4] = (byte) (0xff & length);
    in.readFully(bytes, 5, length);
    return bytes;
  }
</code>
    length > 1G+, for my only 10 terms。readFully wants to read 1G+ bytes but in has not so much bytes，so it throws EOFException。

Revert to R2.15.3+rmr2_2.3.0:+ hadoop 1.2.1 can solve this problem。

**Comment by piccolbo** [comment]
Thanks for looking into this problem. Format changes between 2 and 3 are deep so it's not easy to just look at every diff and fix it. Should still be compatible with typedbytes format describer in HADOOP-1722 Is that 87 a hex number?  What R code are you running, please self contained so that I can try to repro? 87 seems already wrong (it's either 0-12 or >90 in hex). The other thing to debug is writeBin on the R side in  function  rmr2:::typedbytes.writer. As I was developing 3.x errors like this happened when for some reason the length information which goes in the first byte of each key or value is not consistent with the actual record length. Then the rest goes out of alignment and it looks like garbage to the parser. You are saying this is the first byte read on the java side, it looks already wrong so the question is who's writing it.

**Comment by MiguelGodinhoMatos** [comment]
Has anyone come to the bottom of this ? I am having the same problem on my cluster. 

Sometimes some mappers fail with java.io.EOFException. This is totally non deterministic as far as I can tell. In fact sometimes such jobs succeed if the maximum fail thresholds are not reached. 

This only happened to me in jobs that are using the output of other map reduce jobs using the "native.input" format and that have complex structures (e.g. data.frames) in the value argument. 

# The Stderr of a taks that failed:

> Loading objects:
>   b
>   batch_sequence
>   batchn
>   bp
>   comi
>   cumgap
>   dt.comercials
>   dt.comercials_subset
>   hdfs.out
>   hdfs.root
>   i
>   map.eventi
>   map.eventmatch.template
>   map.zapping
>   parse.eventid
>   parse.filelist
>   parsezapping
>   reduce.eventmatch
>   reduce.zapping
>   str_right
>   tmpfiles
>   zappings_comi
> Loading objects:
>   backend.parameters
>   combine
>   combine.file
>   combine.line
>   debug
>   default.input.format
> Warning: S3 methods ‘gorder.default’, ‘gorder.factor’, ‘gorder.data.frame’, ‘gorder.matrix’, ‘gorder.raw’ were declared in NAMESPACE but not found
> Please review your hadoop settings. See help(hadoop.settings)
>   default.output.format
>   in.folder
>   in.memory.combine
>   input.format
>   libs
>   map
>   map.file
>   map.line
>   out.folder
>   output.format
>   pkg.opts
>   postamble
>   preamble
>   profile.nodes
>   reduce
>   reduce.file
>   reduce.line
>   rmr.global.env
>   rmr.local.env
>   save.env
>   tempfile
>   vectorized.reduce
>   verbose
>   work.dir
> Loading required package: methods
> Loading required package: colorout
> Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called ‘colorout’
> Warning in FUN(X[[i]], ...) : can't load colorout
> Loading required package: setwidth
> Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called ‘setwidth’
> Warning in FUN(X[[i]], ...) : can't load setwidth
> Loading required package: vimcom
> Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called ‘vimcom’
> Warning in FUN(X[[i]], ...) : can't load vimcom
> Loading required package: rmr2
> Loading required package: stringr
> Loading required package: data.table
> Loading objects:
>   backend.parameters
>   combine
>   combine.file
>   combine.line
>   debug
>   default.input.format
>   default.output.format
>   in.folder
>   in.memory.combine
>   input.format
>   libs
>   map
>   map.file
>   map.line
>   out.folder
>   output.format
>   pkg.opts
>   postamble
>   preamble
>   profile.nodes
>   reduce
>   reduce.file
>   reduce.line
>   rmr.global.env
>   rmr.local.env
>   save.env
>   tempfile
>   vectorized.reduce
>   verbose
>   work.dir
> Loading required package: lubridate
> Attaching package: ‘lubridate’
> The following objects are masked from ‘package:data.table’:
>     hour, mday, month, quarter, wday, week, yday, year

# The syslog of the task that failed

> 2015-09-02 08:27:36,053 WARN [Thread-12] org.apache.hadoop.streaming.PipeMapRed: java.io.EOFException
> 2015-09-02 08:27:36,057 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.lang.RuntimeException: java.io.EOFException
>     at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:336)
>     at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:535)
>     at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
>     at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
>     at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
>     at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450)
>     at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
>     at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at javax.security.auth.Subject.doAs(Subject.java:415)
>     at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
>     at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
> Caused by: java.io.EOFException
>     at java.io.DataInputStream.readFully(DataInputStream.java:197)
>     at org.apache.hadoop.typedbytes.TypedBytesInput.readRawBytes(TypedBytesInput.java:218)
>     at org.apache.hadoop.typedbytes.TypedBytesInput.readRaw(TypedBytesInput.java:152)
>     at org.apache.hadoop.typedbytes.TypedBytesInput.readRawVector(TypedBytesInput.java:412)
>     at org.apache.hadoop.typedbytes.TypedBytesInput.readRaw(TypedBytesInput.java:144)
>     at org.apache.hadoop.streaming.io.TypedBytesOutputReader.readKeyValue(TypedBytesOutputReader.java:56)
>     at org.apache.hadoop.streaming.PipeMapRed$MROutputThread.run(PipeMapRed.java:378)

I can include the code if you would like to see that as well, but I won't be able to provide you my example. I am working on a couple TB of log files that I can't share. I am trying to see if I can get the same problem on a small job with data that I can share. But because this happens at random times I am having trouble isolating an example that always produces this error. 

# Session Info

I am using Revo R Open

> sessionInfo() 
> R version 3.2.0 (2015-04-16)
> Platform: x86_64-unknown-linux-gnu (64-bit)
> Running under: Red Hat Enterprise Linux
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C  
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C  
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base  
> other attached packages:
> [1] stringr_1.0.0    lubridate_1.3.3  data.table_1.9.4 rhdfs_1.0.8      rJava_0.9-6      rmr2_3.3.1       vimcom_1.2-6     setwidth_1.0-3   colorout_1.1-1  
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.11.5    digest_0.6.8   bitops_1.0-6   chron_2.3-45   plyr_1.8.2     magrittr_1.5   stringi_0.4-1  reshape2_1.4.1 functional_0.6 RJSONIO_1.3-0  tools_3.2.0    caTools_1.17.1 memoise_0.2.1 

# Hadoop Version

Hadoop 2.6.0
Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r e3496499ecb8d220fba99dc5ed4c99c8f9e33bb1
Compiled by jenkins on 2014-11-13T21:10Z
Compiled with protoc 2.5.0
From source with checksum 18e43357c8f927c0695f1e9522859d6a
This command was run using /opt/hadoop/hadoop/share/hadoop/common/hadoop-common-2.6.0.jar
