### ISSUE TITLE
Map reduce not Working with RMR2 / YARN

### ISSUE THREAD

**Issue by akhil29sep** [RevolutionAnalytics/rmr2#113]
R Script

Sys.setenv("HADOOP_CMD"="/usr/lib/hadoop/bin/hadoop")
Sys.setenv("HADOOP_STREAMING"="/usr/lib/hadoop-mapreduce/hadoop-streaming-2.2.0.2.0.6.0-102.jar")
library(rmr2)

map <- function(k,lines) {  
  reg_ndt_disc_group <-strsplit(lines, sep = "|", header=F, stringsAsFactors=F)
  colnames(reg_ndt_disc_group) <- c  ("account_num","sip_endpoint","mac_address","device_firmware","device_ip","proxy_ip","proxy_group","isp","device_type","latitude","longitude","dma_name","dma_code","rn","account","contact_create_date","contact_create_timestamp","account_tenure_categories","category","subcategory_1","subcategory_2","geo_dma","monthly_isp","case_notes","count_care_contacts","did_disc_time","group")  
  reg_ndt_disc_group$contact_create_timestamp <- strptime(reg_ndt_disc_group$contact_create_timestamp, "%m/%d/%Y %I:%M:%S %p")
  return( keyval(reg_ndt_disc_group$sip_endpoint, 1) )  
}

reduce <- function(word, counts) {

  keyval(word, sum(counts))
}

wordcount <- function (input, output=NULL) {

  mapreduce(input=input, output=output, input.format="csv", map=map, reduce=reduce)

}

hdfs.root <- '/vonage'

hdfs.data <- file.path(hdfs.root, 'input_NDT')

hdfs.out <- file.path(hdfs.root, 'out11')

out <- wordcount(hdfs.data, hdfs.out)

 Log Type: syslog

2014-05-30 12:21:22,107 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Created MRAppMaster for application appattempt_1401360535583_0006_000001
2014-05-30 12:21:22,292 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2014-05-30 12:21:22,293 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2014-05-30 12:21:22,393 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Executing with tokens:
2014-05-30 12:21:22,393 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Kind: YARN_AM_RM_TOKEN, Service: , Ident: (org.apache.hadoop.yarn.security.AMRMTokenIdentifier@209444d1)
2014-05-30 12:21:22,411 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: The specific max attempts: 2 for application: 6. Attempt num: 1 is last retry: false
2014-05-30 12:21:22,502 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.retry.interval;  Ignoring.
2014-05-30 12:21:22,503 WARN [main] org.apache.hadoop.conf.Configuration: job.xml:an attempt to override final parameter: mapreduce.job.end-notification.max.attempts;  Ignoring.
2014-05-30 12:21:22,822 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: OutputCommitter set in config null
2014-05-30 12:21:22,823 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: OutputCommitter is org.apache.hadoop.mapred.FileOutputCommitter
2014-05-30 12:21:22,857 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.jobhistory.EventType for class org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler
2014-05-30 12:21:22,858 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.v2.app.job.event.JobEventType for class org.apache.hadoop.mapreduce.v2.app.MRAppMaster$JobEventDispatcher
2014-05-30 12:21:22,858 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.v2.app.job.event.TaskEventType for class org.apache.hadoop.mapreduce.v2.app.MRAppMaster$TaskEventDispatcher
2014-05-30 12:21:22,859 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.v2.app.job.event.TaskAttemptEventType for class org.apache.hadoop.mapreduce.v2.app.MRAppMaster$TaskAttemptEventDispatcher
2014-05-30 12:21:22,859 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.v2.app.commit.CommitterEventType for class org.apache.hadoop.mapreduce.v2.app.commit.CommitterEventHandler
2014-05-30 12:21:22,860 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.v2.app.speculate.Speculator$EventType for class org.apache.hadoop.mapreduce.v2.app.MRAppMaster$SpeculatorEventDispatcher
2014-05-30 12:21:22,860 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.v2.app.rm.ContainerAllocator$EventType for class org.apache.hadoop.mapreduce.v2.app.MRAppMaster$ContainerAllocatorRouter
2014-05-30 12:21:22,861 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncher$EventType for class org.apache.hadoop.mapreduce.v2.app.MRAppMaster$ContainerLauncherRouter
2014-05-30 12:21:22,914 INFO [main] org.apache.hadoop.yarn.event.AsyncDispatcher: Registering class org.apache.hadoop.mapreduce.v2.app.job.event.JobFinishEvent$Type for class org.apache.hadoop.mapreduce.v2.app.MRAppMaster$JobFinishEventHandler
2014-05-30 12:21:23,063 INFO [main] org.apache.hadoop.metrics2.impl.MetricsConfig: loaded properties from hadoop-metrics2.properties
2014-05-30 12:21:23,097 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled snapshot period at 10 second(s).
2014-05-30 12:21:23,097 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MRAppMaster metrics system started
2014-05-30 12:21:23,104 INFO [main] org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl: Adding job token for job_1401360535583_0006 to jobTokenSecretManager
2014-05-30 12:21:23,169 INFO [main] org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl: Not uberizing job_1401360535583_0006 because: not enabled; too much RAM;
2014-05-30 12:21:23,186 INFO [main] org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl: Input size for job job_1401360535583_0006 = 3397011. Number of splits = 2
2014-05-30 12:21:23,187 INFO [main] org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl: Number of reduces for job job_1401360535583_0006 = 1
2014-05-30 12:21:23,187 INFO [main] org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl: job_1401360535583_0006Job Transitioned from NEW to INITED
2014-05-30 12:21:23,188 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: MRAppMaster launching normal, non-uberized, multi-container job job_1401360535583_0006.
2014-05-30 12:21:23,216 INFO [Socket Reader #1 for port 36300] org.apache.hadoop.ipc.Server: Starting Socket Reader #1 for port 36300
2014-05-30 12:21:23,227 INFO [main] org.apache.hadoop.yarn.factories.impl.pb.RpcServerFactoryPBImpl: Adding protocol org.apache.hadoop.mapreduce.v2.api.MRClientProtocolPB to the server
2014-05-30 12:21:23,228 INFO [IPC Server Responder] org.apache.hadoop.ipc.Server: IPC Server Responder: starting
2014-05-30 12:21:23,228 INFO [IPC Server listener on 36300] org.apache.hadoop.ipc.Server: IPC Server listener on 36300: starting
2014-05-30 12:21:23,229 INFO [main] org.apache.hadoop.mapreduce.v2.app.client.MRClientService: Instantiated MRClientService at doremon.aerisdev.net/192.168.213.54:36300
2014-05-30 12:21:23,255 INFO [main] org.mortbay.log: Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
2014-05-30 12:21:23,290 INFO [main] org.apache.hadoop.http.HttpServer: Added global filter 'safety' (class=org.apache.hadoop.http.HttpServer$QuotingInputFilter)
2014-05-30 12:21:23,292 INFO [main] org.apache.hadoop.http.HttpServer: Added filter AM_PROXY_FILTER (class=org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter) to context mapreduce
2014-05-30 12:21:23,292 INFO [main] org.apache.hadoop.http.HttpServer: Added filter AM_PROXY_FILTER (class=org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter) to context static
2014-05-30 12:21:23,295 INFO [main] org.apache.hadoop.http.HttpServer: adding path spec: /mapreduce/*
2014-05-30 12:21:23,295 INFO [main] org.apache.hadoop.http.HttpServer: adding path spec: /ws/*
2014-05-30 12:21:23,295 INFO [main] org.apache.hadoop.http.HttpServer: Jetty bound to port 33637
2014-05-30 12:21:23,295 INFO [main] org.mortbay.log: jetty-6.1.26
2014-05-30 12:21:23,314 INFO [main] org.mortbay.log: Extract jar:file:/usr/lib/hadoop-yarn/hadoop-yarn-common-2.2.0.2.0.6.0-102.jar!/webapps/mapreduce to /tmp/Jetty_0_0_0_0_33637_mapreduce____po04e7/webapp
2014-05-30 12:21:23,462 INFO [main] org.mortbay.log: Started SelectChannelConnector@0.0.0.0:33637
2014-05-30 12:21:23,462 INFO [main] org.apache.hadoop.yarn.webapp.WebApps: Web app /mapreduce started at 33637
2014-05-30 12:21:23,688 INFO [main] org.apache.hadoop.yarn.webapp.WebApps: Registered webapp guice modules
2014-05-30 12:21:23,691 INFO [Socket Reader #1 for port 39557] org.apache.hadoop.ipc.Server: Starting Socket Reader #1 for port 39557
2014-05-30 12:21:23,694 INFO [IPC Server Responder] org.apache.hadoop.ipc.Server: IPC Server Responder: starting
2014-05-30 12:21:23,694 INFO [IPC Server listener on 39557] org.apache.hadoop.ipc.Server: IPC Server listener on 39557: starting
2014-05-30 12:21:23,711 INFO [main] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerRequestor: nodeBlacklistingEnabled:true
2014-05-30 12:21:23,711 INFO [main] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerRequestor: maxTaskFailuresPerNode is 3
2014-05-30 12:21:23,711 INFO [main] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerRequestor: blacklistDisablePercent is 33
2014-05-30 12:21:23,729 INFO [main] org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at doremon.aerisdev.net/192.168.213.54:8030
2014-05-30 12:21:23,753 INFO [main] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: maxContainerCapability: 4096
2014-05-30 12:21:23,754 INFO [main] org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl: Upper limit on the thread pool size is 500
2014-05-30 12:21:23,755 INFO [main] org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy: yarn.client.max-nodemanagers-proxies : 500
2014-05-30 12:21:23,759 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl: job_1401360535583_0006Job Transitioned from INITED to SETUP
2014-05-30 12:21:23,760 INFO [CommitterEvent Processor #0] org.apache.hadoop.mapreduce.v2.app.commit.CommitterEventHandler: Processing the event EventType: JOB_SETUP
2014-05-30 12:21:23,800 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.JobImpl: job_1401360535583_0006Job Transitioned from SETUP to RUNNING
2014-05-30 12:21:23,814 INFO [AsyncDispatcher event handler] org.apache.hadoop.yarn.util.RackResolver: Resolved doremon.aerisdev.net to /default-rack
2014-05-30 12:21:23,821 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskImpl: task_1401360535583_0006_m_000000 Task Transitioned from NEW to SCHEDULED
2014-05-30 12:21:23,821 INFO [AsyncDispatcher event handler] org.apache.hadoop.yarn.util.RackResolver: Resolved doremon.aerisdev.net to /default-rack
2014-05-30 12:21:23,821 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskImpl: task_1401360535583_0006_m_000001 Task Transitioned from NEW to SCHEDULED
2014-05-30 12:21:23,821 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskImpl: task_1401360535583_0006_r_000000 Task Transitioned from NEW to SCHEDULED
2014-05-30 12:21:23,822 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: attempt_1401360535583_0006_m_000000_0 TaskAttempt Transitioned from NEW to UNASSIGNED
2014-05-30 12:21:23,822 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: attempt_1401360535583_0006_m_000001_0 TaskAttempt Transitioned from NEW to UNASSIGNED
2014-05-30 12:21:23,822 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: attempt_1401360535583_0006_r_000000_0 TaskAttempt Transitioned from NEW to UNASSIGNED
2014-05-30 12:21:23,824 INFO [Thread-48] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: mapResourceReqt:2000
2014-05-30 12:21:23,830 INFO [Thread-48] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: reduceResourceReqt:2000
2014-05-30 12:21:23,857 INFO [eventHandlingThread] org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler: Event Writer setup for JobId: job_1401360535583_0006, File: hdfs://doremon.aerisdev.net:8020/user/root/.staging/job_1401360535583_0006/job_1401360535583_0006_1.jhist
2014-05-30 12:21:23,875 INFO [eventHandlingThread] org.apache.hadoop.conf.Configuration.deprecation: user.name is deprecated. Instead, use mapreduce.job.user.name
2014-05-30 12:21:24,753 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Before Scheduling: PendingReds:1 ScheduledMaps:2 ScheduledReds:0 AssignedMaps:0 AssignedReds:0 CompletedMaps:0 CompletedReds:0 ContAlloc:0 ContRel:0 HostLocal:0 RackLocal:0
2014-05-30 12:21:24,771 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerRequestor: getResources() for application_1401360535583_0006: ask=3 release= 0 newContainers=0 finishedContainers=0 resourcelimit=<memory:3072, vCores:0> knownNMs=1
2014-05-30 12:21:24,772 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Recalculating schedule, headroom=3072
2014-05-30 12:21:24,772 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Reduce slow start threshold not met. completedMapsForReduceSlowstart 1
2014-05-30 12:21:25,780 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Got allocated containers 1
2014-05-30 12:21:25,780 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Assigned container container_1401360535583_0006_01_000002 to attempt_1401360535583_0006_m_000000_0
2014-05-30 12:21:25,781 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Recalculating schedule, headroom=1024
2014-05-30 12:21:25,781 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: Reduce slow start threshold not met. completedMapsForReduceSlowstart 1
2014-05-30 12:21:25,781 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerAllocator: After Scheduling: PendingReds:1 ScheduledMaps:1 ScheduledReds:0 AssignedMaps:1 AssignedReds:0 CompletedMaps:0 CompletedReds:0 ContAlloc:1 ContRel:0 HostLocal:1 RackLocal:0
2014-05-30 12:21:25,797 INFO [AsyncDispatcher event handler] org.apache.hadoop.yarn.util.RackResolver: Resolved doremon.aerisdev.net to /default-rack
2014-05-30 12:21:25,807 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: The job-jar file on the remote FS is hdfs://doremon.aerisdev.net:8020/user/root/.staging/job_1401360535583_0006/job.jar
2014-05-30 12:21:25,809 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: The job-conf file on the remote FS is /user/root/.staging/job_1401360535583_0006/job.xml
2014-05-30 12:21:25,815 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Adding #0 tokens and #1 secret keys for NM use for launching container
2014-05-30 12:21:25,815 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Size of containertokens_dob is 1
2014-05-30 12:21:25,815 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Putting shuffle token in serviceData
2014-05-30 12:21:25,829 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: attempt_1401360535583_0006_m_000000_0 TaskAttempt Transitioned from UNASSIGNED to ASSIGNED
2014-05-30 12:21:25,837 INFO [ContainerLauncher #0] org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl: Processing the event EventType: CONTAINER_REMOTE_LAUNCH for container container_1401360535583_0006_01_000002 taskAttempt attempt_1401360535583_0006_m_000000_0
2014-05-30 12:21:25,838 INFO [ContainerLauncher #0] org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl: Launching attempt_1401360535583_0006_m_000000_0
2014-05-30 12:21:25,839 INFO [ContainerLauncher #0] org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy: Opening proxy : doremon.aerisdev.net:45454
2014-05-30 12:21:25,873 INFO [ContainerLauncher #0] org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl: Shuffle port returned by ContainerManager for attempt_1401360535583_0006_m_000000_0 : 13562
2014-05-30 12:21:25,874 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: TaskAttempt: [attempt_1401360535583_0006_m_000000_0] using containerId: [container_1401360535583_0006_01_000002 on NM: [doremon.aerisdev.net:45454]
2014-05-30 12:21:25,876 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: attempt_1401360535583_0006_m_000000_0 TaskAttempt Transitioned from ASSIGNED to RUNNING
2014-05-30 12:21:25,876 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskImpl: task_1401360535583_0006_m_000000 Task Transitioned from SCHEDULED to RUNNING
2014-05-30 12:21:26,698 INFO [Socket Reader #1 for port 39557] SecurityLogger.org.apache.hadoop.ipc.Server: Auth successful for job_1401360535583_0006 (auth:SIMPLE)
2014-05-30 12:21:26,715 INFO [IPC Server handler 0 on 39557] org.apache.hadoop.mapred.TaskAttemptListenerImpl: JVM with ID : jvm_1401360535583_0006_m_000002 asked for a task
2014-05-30 12:21:26,715 INFO [IPC Server handler 0 on 39557] org.apache.hadoop.mapred.TaskAttemptListenerImpl: JVM with ID: jvm_1401360535583_0006_m_000002 given task: attempt_1401360535583_0006_m_000000_0
2014-05-30 12:21:26,783 INFO [RMCommunicator Allocator] org.apache.hadoop.mapreduce.v2.app.rm.RMContainerRequestor: getResources() for application_1401360535583_0006: ask=3 release= 0 newContainers=0 finishedContainers=0 resourcelimit=<memory:1024, vCores:-1> knownNMs=1
2014-05-30 12:21:28,040 INFO [IPC Server handler 1 on 39557] org.apache.hadoop.mapred.TaskAttemptListenerImpl: Status update from attempt_1401360535583_0006_m_000000_0
2014-05-30 12:21:28,040 INFO [IPC Server handler 1 on 39557] org.apache.hadoop.mapred.TaskAttemptListenerImpl: Progress of TaskAttempt attempt_1401360535583_0006_m_000000_0 is : 0.0
2014-05-30 12:21:28,047 FATAL [IPC Server handler 2 on 39557] org.apache.hadoop.mapred.TaskAttemptListenerImpl: Task: attempt_1401360535583_0006_m_000000_0 - exited : java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
    at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
    at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:429)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:162)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:157)

2014-05-30 12:21:28,047 INFO [IPC Server handler 2 on 39557] org.apache.hadoop.mapred.TaskAttemptListenerImpl: Diagnostics report from attempt_1401360535583_0006_m_000000_0: Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
    at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
    at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:429)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:162)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:157)

2014-05-30 12:21:28,048 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Diagnostics report from attempt_1401360535583_0006_m_000000_0: Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
    at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:320)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:533)
    at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
    at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:429)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:162)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:157)

**Comment by shartoo** [comment]
Is there any information about the error "rmr was not able to read file"?
