### ISSUE TITLE
from.dfs(): Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ddreyfus** [RevolutionAnalytics/rmr2#123]
rmr v 3.1.1
Reading a file from hdfs that is 498,194,638 bytes.

I get the following error. Which parameters need to be adjusted, and where would they be set, to avoid this problem? The node from which I am running has 30GB RAM.

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at org.apache.hadoop.io.DataOutputBuffer$Buffer.write(DataOutputBuffer.java:66)
        at org.apache.hadoop.io.DataOutputBuffer.write(DataOutputBuffer.java:120)
        at org.apache.hadoop.io.SequenceFile$Reader.next(SequenceFile.java:2368)
        at org.apache.hadoop.io.SequenceFile$Reader.next(SequenceFile.java:2500)
        at org.apache.hadoop.mapred.SequenceFileRecordReader.next(SequenceFileRecordReader.java:82)
        at org.apache.hadoop.streaming.DumpTypedBytes.dumpTypedBytes(DumpTypedBytes.java:118)
        at org.apache.hadoop.streaming.DumpTypedBytes.run(DumpTypedBytes.java:88)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at org.apache.hadoop.streaming.HadoopStreaming.main(HadoopStreaming.java:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

**Comment by dkenchamba** [comment]
By default the Heapsize setting is 256MB. This can be increased by modifying environment variable 'HADOOP_CLIENT_OPTS' as below
export HADOOP_CLIENT_OPTS='-Xms1g -Xmx1g -Djava.net.preferIPv4Stack=true'

Deepak Kenchamba, Trianz BigData CCoE
http://www.trianz.com/
