### ISSUE TITLE
problems executing mapreduce under cloudera 4.3 cluster on amazon

### ISSUE THREAD

**Issue by fcastanedo** [RevolutionAnalytics/rmr2#66]
Hello,
We are trying to execute a RHadoop mapreduce example under a Cloudera cluster 4.3 deployed on Amazon and experienced some problems with the current code on github.
The R script execution fails. However trying an example directly calling Hadoop streaming both in the R console with system() and in the bash console works and distributes the tasks to the other nodes.

This is the output of the final.commad invoked at streaming.R:

/usr/bin/hadoop jar /usr/lib/hadoop-0.20-mapreduce/contrib/streaming/hadoop-streaming-2.0.0-mr1-cdh4.3.0.jar    -D     'stream.map.output=typedbytes'     -D     'stream.reduce.input=typedbytes'     -D     'stream.reduce.output=typedbytes'      -input     'hdfs:///user/ubuntu/input_1may.csv'     -output     '/tmp/RtmpucMYt5/file4482f5cd8da'     -mapper     'Rscript ./rmr-streaming-map448219b7436'      -reducer     'Rscript ./rmr-streaming-reduce448275b0f5bf'   -file /tmp/RtmpucMYt5/rmr-local-env448279bf432f -file /tmp/RtmpucMYt5/rmr-global-env448265c1de2f   -file     '/tmp/RtmpucMYt5/rmr-streaming-map448219b7436'     -file     '/tmp/RtmpucMYt5/rmr-streaming-reduce448275b0f5bf'       -outputformat     'org.apache.hadoop.mapred.SequenceFileOutputFormat'

In the JobTracker we got the following error:

2013-08-26 14:32:22,935 INFO org.apache.hadoop.mapred.JobInProgress: Choosing a failed task task_201308261012_0035_m_000000
2013-08-26 14:32:22,935 WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2013-08-26 14:32:22,936 INFO org.apache.hadoop.mapred.JobTracker: Adding task (MAP) 'attempt_201308261012_0035_m_000000_1' to tip task_201308261012_0035_m_000000, for tracker 'tracker_ip-10-0-0-93.us-west-2.compute.internal:localhost/127.0.0.1:44307'
2013-08-26 14:32:22,937 INFO org.apache.hadoop.mapred.JobInProgress: Choosing data-local task task_201308261012_0035_m_000000
2013-08-26 14:32:22,937 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201308261012_0035_m_000002_0'
2013-08-26 14:32:32,390 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201308261012_0035_m_000001_0: java.io.IOException: log:null
R/W/S=11056/0/0 in:153=11056/72 [rec/s] out:0=0/72 [rec/s]
minRecWrittenToEnableSkip_=9223372036854775807 LOGNAME=null
HOST=null
USER=null
HADOOP_USER=null
last Hadoop input: |null|
last tool output: |null|
Date: Mon Aug 26 14:32:31 UTC 2013
java.io.IOException: Broken pipe
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:282)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:105)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:109)
    at java.io.DataOutputStream.write(DataOutputStream.java:90)
    at org.apache.hadoop.streaming.io.TextInputWriter.writeUTF8(TextInputWriter.java:72)
    at org.apache.hadoop.streaming.io.TextInputWriter.writeValue(TextInputWriter.java:51)
    at org.apache.hadoop.streaming.PipeMapper.map(PipeMapper.java:110)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:50)
    at org.apache.hadoop.s
2013-08-26 14:32:35,720 INFO org.apache.hadoop.mapred.JobInProgress: Choosing a failed task task_201308261012_0035_m_000002
2013-08-26 14:32:35,720 WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2013-08-26 14:32:35,723 INFO org.apache.hadoop.mapred.JobTracker: Adding task (MAP) 'attempt_201308261012_0035_m_000002_1' to tip task_201308261012_0035_m_000002, for tracker 'tracker_ip-10-0-0-94.us-west-2.compute.internal:localhost/127.0.0.1:47203'
2013-08-26 14:32:35,723 INFO org.apache.hadoop.mapred.JobInProgress: Choosing data-local task task_201308261012_0035_m_000002
2013-08-26 14:32:35,724 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201308261012_0035_m_000001_0'

and in the TaskTracker of one node:
2013-08-26 13:08:26,474 INFO org.apache.hadoop.mapred.TaskTracker: attempt_201308261012_0033_m_000001_0 0.0% 
2013-08-26 13:08:26,723 INFO org.apache.hadoop.mapred.TaskTracker: Received commit task action for attempt_201308261012_0033_m_000001_0
2013-08-26 13:08:27,540 INFO org.apache.hadoop.mapred.TaskTracker: attempt_201308261012_0033_m_000001_0 1.0% Records R/W=7/1
2013-08-26 13:08:27,542 INFO org.apache.hadoop.mapred.TaskTracker: Task attempt_201308261012_0033_m_000001_0 is done.
2013-08-26 13:08:27,542 INFO org.apache.hadoop.mapred.TaskTracker: reported output size for attempt_201308261012_0033_m_000001_0  was -1
2013-08-26 13:08:27,542 INFO org.apache.hadoop.mapred.TaskTracker: addFreeSlot : current free slots : 1
2013-08-26 13:08:27,622 INFO org.apache.hadoop.mapred.JvmManager: JVM : jvm_201308261012_0033_m_1287114602 exited with exit code 0. Number of tasks it ran: 1
2013-08-26 13:08:51,537 INFO org.apache.hadoop.mapred.TaskTracker: Received 'KillJobAction' for job: job_201308261012_0033
2013-08-26 13:08:51,537 INFO org.apache.hadoop.mapred.IndexCache: Map ID attempt_201308261012_0033_m_000001_0 not found in cache
2013-08-26 13:08:51,541 INFO org.apache.hadoop.mapred.UserLogCleaner: Adding job_201308261012_0033 for user-log deletion with retainTimeStamp:1377608931539
2013-08-26 14:31:13,183 WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2013-08-26 14:31:13,185 INFO org.apache.hadoop.mapred.TaskTracker: LaunchTaskAction (registerTask): attempt_201308261012_0035_m_000001_0 task's state:UNASSIGNED
2013-08-26 14:31:13,185 INFO org.apache.hadoop.mapred.TaskTracker: Trying to launch : attempt_201308261012_0035_m_000001_0 which needs 1 slots
2013-08-26 14:31:13,185 INFO org.apache.hadoop.mapred.TaskTracker: In TaskLauncher, current free slots : 1 and trying to launch attempt_201308261012_0035_m_000001_0 which needs 1 slots
2013-08-26 14:31:13,247 INFO org.apache.hadoop.mapred.JobLocalizer: Initializing user ubuntu on this TT.
2013-08-26 14:31:13,340 INFO org.apache.hadoop.mapred.JvmManager: In JvmRunner constructed JVM ID: jvm_201308261012_0035_m_-861963920
2013-08-26 14:31:13,341 INFO org.apache.hadoop.mapred.JvmManager: JVM Runner jvm_201308261012_0035_m_-861963920 spawned.
2013-08-26 14:31:13,343 INFO org.apache.hadoop.mapred.TaskController: Writing commands to /mnt/mapred/local/ttprivate/taskTracker/ubuntu/jobcache/job_201308261012_0035/attempt_201308261012_0035_m_000001_0/taskjvm.sh
2013-08-26 14:31:15,770 INFO org.apache.hadoop.mapred.TaskTracker: JVM with ID: jvm_201308261012_0035_m_-861963920 given task: attempt_201308261012_0035_m_000001_0
2013-08-26 14:31:24,051 INFO org.apache.hadoop.mapred.TaskTracker: attempt_201308261012_0035_m_000001_0 0.008785891% hdfs://ip-10-0-0-93.us-west-2.compute.internal:8020/user/ubuntu/input_1may.csv:134217728+134217728
2013-08-26 14:32:31,965 INFO org.apache.hadoop.mapred.TaskTracker: attempt_201308261012_0035_m_000001_0 0.008785891% hdfs://ip-10-0-0-93.us-west-2.compute.internal:8020/user/ubuntu/input_1may.csv:134217728+134217728
2013-08-26 14:32:32,102 INFO org.apache.hadoop.mapred.TaskStatus: task-diagnostic-info for task attempt_201308261012_0035_m_000001_0 : java.io.IOException: log:null
R/W/S=11056/0/0 in:153=11056/72 [rec/s] out:0=0/72 [rec/s]
minRecWrittenToEnableSkip_=9223372036854775807 LOGNAME=null
HOST=null
USER=null
HADOOP_USER=null
last Hadoop input: |null|
last tool output: |null|
Date: Mon Aug 26 14:32:31 UTC 2013
java.io.IOException: Broken pipe
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:282)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:105)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:109)
    at java.io.DataOutputStream.write(DataOutputStream.java:90)
    at org.apache.hadoop.streaming.io.TextInputWriter.writeUTF8(TextInputWriter.java:72)
    at org.apache.hadoop.streaming.io.TextInputWriter.writeValue(TextInputWriter.java:51)
    at org.apache.hadoop.streaming.PipeMapper.map(PipeMapper.java:110)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:50)
    at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)

```
at org.apache.hadoop.streaming.PipeMapper.map(PipeMapper.java:126)
at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:50)
at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:396)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
at org.apache.hadoop.mapred.Child.main(Child.java:262)
```

2013-08-26 14:32:32,280 INFO org.apache.hadoop.mapred.JvmManager: JVM : jvm_201308261012_0035_m_-861963920 exited with exit code 0. Number of tasks it ran: 0
2013-08-26 14:32:35,281 INFO org.apache.hadoop.mapred.TaskTracker: addFreeSlot : current free slots : 1
2013-08-26 14:32:35,439 WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2013-08-26 14:32:35,440 INFO org.apache.hadoop.mapred.TaskTracker: LaunchTaskAction (registerTask): attempt_201308261012_0035_m_000002_1 task's state:UNASSIGNED
2013-08-26 14:32:35,440 INFO org.apache.hadoop.mapred.TaskTracker: Trying to launch : attempt_201308261012_0035_m_000002_1 which needs 1 slots
2013-08-26 14:32:35,441 INFO org.apache.hadoop.mapred.TaskTracker: In TaskLauncher, current free slots : 1 and trying to launch attempt_201308261012_0035_m_000002_1 which needs 1 slots
2013-08-26 14:32:35,521 INFO org.apache.hadoop.mapred.JvmManager: In JvmRunner constructed JVM ID: jvm_201308261012_0035_m_-1565583762
2013-08-26 14:32:35,521 INFO org.apache.hadoop.mapred.JvmManager: JVM Runner jvm_201308261012_0035_m_-1565583762 spawned.
2013-08-26 14:32:35,545 INFO org.apache.hadoop.mapred.TaskController: Writing commands to /mnt/mapred/local/ttprivate/taskTracker/ubuntu/jobcache/job_201308261012_0035/attempt_201308261012_0035_m_000002_1/taskjvm.sh
2013-08-26 14:32:40,179 INFO org.apache.hadoop.mapred.TaskTracker: JVM with ID: jvm_201308261012_0035_m_-1565583762 given task: attempt_201308261012_0035_m_000002_1
2013-08-26 14:32:48,967 INFO org.apache.hadoop.mapred.TaskTracker: attempt_201308261012_0035_m_000002_1 0.008785831% hdfs://ip-10-0-0-93.us-west-2.compute.internal:8020/user/ubuntu/input_1may.csv:268435456+134217728
2013-08-26 14:32:52,015 INFO org.apache.hadoop.mapred.TaskTracker: attempt_201308261012_0035_m_000002_1 0.008785831% hdfs://ip-10-0-0-93.us-west-2.compute.internal:8020/user/ubuntu/input_1may.csv:268435456+

Any idea about what can be the problem?

Thanks,
Federico

**Comment by LIXUlixu123** [comment]
fool
